<h1> <font color="red"> Period of a TPM </font> </h1>

In [1]:
import math
import numpy as np

a=np.array([
    [0.2,0.5,0.3,0],#1st row...
    [0.1,0.3,0.6,0],#2nd row...
    [0,0.4,0.3,0.3],#3rd row...
    [0,0,0.5,0.5]#4th row
])
print("\nTransition Probability Matrix(TPM): \n",a)


an=np.dot(a,a)
print(f"\nP^2 : ")
print(an.round(decimals=4))
print()

states=[]
m=1#d(s)=Tss
n=1#d(s)=Tss


# Next occurances
for i in range(3,33):
    an=np.dot(an,a)
    print(f"P^{i} : ")
    print(an.round(decimals=4))
    print()
    if an[m][n]!=0:
        states.append(i)
print(f"\nStates: {states}")

#Gcd 
m=math.gcd(states[0],states[1])
for s in range(2,len(states)):
    m=math.gcd(m,states[s])
print(f"\nGCD: {m}")


Transition Probability Matrix(TPM): 
 [[0.2 0.5 0.3 0. ]
 [0.1 0.3 0.6 0. ]
 [0.  0.4 0.3 0.3]
 [0.  0.  0.5 0.5]]

P^2 : 
[[0.09 0.37 0.45 0.09]
 [0.05 0.38 0.39 0.18]
 [0.04 0.24 0.48 0.24]
 [0.   0.2  0.4  0.4 ]]

P^3 : 
[[0.055 0.336 0.429 0.18 ]
 [0.048 0.295 0.45  0.207]
 [0.032 0.284 0.42  0.264]
 [0.02  0.22  0.44  0.32 ]]

P^4 : 
[[0.0446 0.2999 0.4368 0.2187]
 [0.0391 0.2925 0.4299 0.2385]
 [0.0348 0.2692 0.438  0.258 ]
 [0.026  0.252  0.43   0.292 ]]

P^5 : 
[[0.0389 0.287  0.4337 0.2404]
 [0.0371 0.2793 0.4354 0.2482]
 [0.0339 0.2734 0.4324 0.2604]
 [0.0304 0.2606 0.434  0.275 ]]

P^6 : 
[[0.0365 0.279  0.4342 0.2503]
 [0.0353 0.2765 0.4334 0.2547]
 [0.0341 0.2719 0.4341 0.2599]
 [0.0321 0.267  0.4332 0.2677]]

P^7 : 
[[0.0352 0.2756 0.4338 0.2554]
 [0.0347 0.274  0.4339 0.2574]
 [0.034  0.2723 0.4335 0.2602]
 [0.0331 0.2694 0.4336 0.2638]]

P^8 : 
[[0.0346 0.2738 0.4338 0.2578]
 [0.0343 0.2731 0.4337 0.2589]
 [0.034  0.2721 0.4337 0.2602]
 [0.0336 0.2708 0.4336 0.262 ]]



In [39]:
a=np.array([
        [0.7,0,0.3,0],#1st row...
        [0.5,0,0.5,0],#2nd row...
        [0,0.4,0,0.6],#3rd row...
        [0,0.2,0,0.8]#4th row
])#row-wise...!!!
print("\nTransition Probability Matrix(TPM): \n",a.round(decimals=4))
a2=np.dot(a,a.round(decimals=4))
print("\nP^2: \n",a2.round(decimals=4))
a3=np.dot(a2,a)
print("\nP^3: \n",a3.round(decimals=4))
a4=np.dot(a2,a2)
print("\nP^4: \n",a4.round(decimals=4))


Transition Probability Matrix(TPM): 
 [[0.7 0.  0.3 0. ]
 [0.5 0.  0.5 0. ]
 [0.  0.4 0.  0.6]
 [0.  0.2 0.  0.8]]

P^2: 
 [[0.49 0.12 0.21 0.18]
 [0.35 0.2  0.15 0.3 ]
 [0.2  0.12 0.2  0.48]
 [0.1  0.16 0.1  0.64]]

P^3: 
 [[0.403 0.12  0.207 0.27 ]
 [0.345 0.12  0.205 0.33 ]
 [0.2   0.176 0.12  0.504]
 [0.15  0.168 0.11  0.572]]

P^4: 
 [[0.3421 0.1368 0.1809 0.3402]
 [0.3015 0.148  0.1635 0.387 ]
 [0.228  0.1488 0.148  0.4752]
 [0.189  0.1584 0.129  0.5236]]


<h3>State probability?</h3>

In [35]:
P=np.array([
    [0.2,0.5,0.3,0],#1st row...
    [0.1,0.3,0.6,0],#2nd row...
    [0,0.4,0.3,0.3],#3rd row...
    [0,0,0.5,0.5]#4th row
])
A=np.array(
    [0,0,0,1]
)
for i in range(10):
    print(f"n={i+1}",np.dot(A,P))
    A=np.dot(A,P)

n=1 [0.  0.  0.5 0.5]
n=2 [0.  0.2 0.4 0.4]
n=3 [0.02 0.22 0.44 0.32]
n=4 [0.026 0.252 0.43  0.292]
n=5 [0.0304 0.2606 0.434  0.275 ]
n=6 [0.03214 0.26698 0.43318 0.2677 ]
n=7 [0.033126 0.269436 0.433634 0.263804]
n=8 [0.0335688 0.2708474 0.4335916 0.2619922]
n=9 [0.0337985  0.27147526 0.43365266 0.26107358]
n=10 [0.03390723 0.27180289 0.43365729 0.26063259]


<h1> <font color="red"> Limiting distribution </font> </h1>

<h2> <font color="blue"> Method: 01 </font> </h2>

In [36]:
import numpy as np
import math
import pandas
# import fractions
# np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x))})

P=np.array([
        [0.7,0,0.3,0],#1st row...
        [0.5,0,0.5,0],#2nd row...
        [0,0.4,0,0.6],#3rd row...
        [0,0.2,0,0.8]#4th row
])#row-wise...!!!


an=np.dot(P,P)
t2=an.round(decimals=4)
tn=an.round(decimals=4)


for n in range(3,1025):
    an=np.dot(an,P)
    if n in [4,8,16,32,64,128,512,1024]:
        if an.round(decimals=4).tolist()==tn.tolist():
            print("n = ",n-n//2)
            break
        else:
            tn=an.round(decimals=4)

n =  32


$P^2$

In [37]:
pandas.DataFrame(t2)

0     1     2     3
0  0.49  0.12  0.21  0.18
1  0.35  0.20  0.15  0.30
2  0.20  0.12  0.20  0.48
3  0.10  0.16  0.10  0.64

$P^n$

In [38]:
pandas.DataFrame(tn)

0     1     2     3
0  0.25  0.15  0.15  0.45
1  0.25  0.15  0.15  0.45
2  0.25  0.15  0.15  0.45
3  0.25  0.15  0.15  0.45

<h2> <font color="blue"> Method: 02 </font> </h2>

In [16]:
from scipy import linalg
import math
import numpy as np
import pandas



# c0=[]#1st column...
# c1=[]#2nd column...

# P0=[c0[0]-1,c0[1],c0[2]]#3X3
# P1=[c1[0],c1[1]-1,c1[2]]#3X3
# P= linalg.solve(np.array([P0,P1,P2,[1,1,1]]), np.array([0,0,1]))

# vector=np.array([
#                 [P[0],P[1],P[2]],
#                 [P[0],P[1],P[2]],
#                 [P[0],P[1],P[2]]]
# )#3X3

# -----------------------------------------------------------------------------------------------------------------------------------------------------------------

c0=[1/4,0,0,1/2]#1st column...
c1=[1/4,1/3,0,1/4]#2nd column...
c2=[1/4,1/3,1/2,0]#3rd column...

P0=[c0[0]-1,c0[1],c0[2],c0[3]]#4X4
P1=[c1[0],c1[1]-1,c1[2],c1[3]]#4X4
P2=[c2[0],c2[1],c2[2]-1,c2[3]]#4X4
P= linalg.solve(np.array([P0,P1,P2,[1,1,1,1]]), np.array([0,0,0,1]))#4X4

vector=np.array([
                 [P[0],P[1],P[2],P[3]],
                 [P[0],P[1],P[2],P[3]],
                 [P[0],P[1],P[2],P[3]],
                 [P[0],P[1],P[2],P[3]]
])#4X4

# -----------------------------------------------------------------------------------------------------------------------------------------------------------------

print("\nSteady state probability: ",P.round(decimals=4))#3X3 or 4X4

print("\nStable matrix: \n")#3X3 or 4X4
pandas.DataFrame(vector.round(decimals=4))


Steady state probability:  [0.2192 0.2055 0.2466 0.3288]

Stable matrix: 



0       1       2       3
0  0.2192  0.2055  0.2466  0.3288
1  0.2192  0.2055  0.2466  0.3288
2  0.2192  0.2055  0.2466  0.3288
3  0.2192  0.2055  0.2466  0.3288

<h1> <font color="red"> TPM probability for differet time point or Trajectory </font> </h1>

In [ ]:
matrix=np.array(
[
        [],#1st row...
        [],#2nd row...
        []#3rd row...
]
)
matrix2=np.dot(matrix,matrix)
print(matrix2)

In [ ]:
matrix=[
        [],#1st row...
        [],#2nd row...
        []#3rd row...
]

path=[]#trajectory
steps=[]#len(path)-1
distribution=[]
P=distribution[path[0]-1]
for i in range(1,len(path)):
    print(">>>",matrix[path[i-1]-1][path[i]-1])
    P*=matrix[path[i-1]-1][path[i]-1]
print("\nProbability: ",P)

$P(X_n=c|X_i=r)=P^{n-i}_{rc}$

In [ ]:
m=np.array(
[
        [],#1st row...
        [],#2nd row...
        []#3rd row...
]
)
s=[]#P_rc
t=[]#initial->jumping state
if t[1]-t[0]>1:
    n=np.dot(m,m)
    for i in range(2,t[1]-t[0]):
        n=np.dot(n,m)
    print(n)
    print("\nProbability: ",round(n[s[0]-1][s[1]-1],2))
else:
    print(m)
    print("\nProbability: ",round(m[s[0]-1][s[1]-1],2))